
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartns550.h"

/*
 * The configuration table for devices
 */

XUartNs550_Config XUartNs550_ConfigTable[] =
{
	{
		XPAR_UARTNS550_0_DEVICE_ID,
		XPAR_UARTNS550_0_BASEADDR,
		XPAR_UARTNS550_0_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_1_DEVICE_ID,
		XPAR_UARTNS550_1_BASEADDR,
		XPAR_UARTNS550_1_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_2_DEVICE_ID,
		XPAR_UARTNS550_2_BASEADDR,
		XPAR_UARTNS550_2_CLOCK_FREQ_HZ
	},
	{
		XPAR_UARTNS550_3_DEVICE_ID,
		XPAR_UARTNS550_3_BASEADDR,
		XPAR_UARTNS550_3_CLOCK_FREQ_HZ
	}
};


